from pathlib import Path
p=Path('static-web/scripts/test-xizong-final-independent.mjs');s=p.read_text()
s=s.replace("'digestive-d01'","'D1'")
s=s.replace("import { spawn }", "import { spawn, execFileSync }")
s=s.replace("import { loadXizongBlock, listProjectableXizongSystems }", "import { loadXizongBlock, loadXizongSystem, listProjectableXizongSystems }")
s=s.replace("import { loadXizongWholePaper }", "import { loadXizongWholePaper, loadXizongSystemQuestionSweep }")
s=s.replace("const root=path.resolve('..');", """import os from 'node:os';
import { resolveXizongLearnerProjection } from '../src/lib/xizongLearnerProjection.mjs';
import { releaseCompletedBlockToMemory } from '../src/lib/xizongMemoryAutoRelease.mjs';
import { todayMemoryQueue, setRepairTasks, completeRepairTask, XIZONG_MEMORY_STORAGE_KEY } from '../src/lib/xizongMemoryModel.mjs';
import { ensureXizongQuestionSweepState, recordXizongQuestionAttempt, startNextXizongQuestionRound, deriveXizongSecondPassQuestionIds, setXizongQuestionMarked, deriveXizongMarkedQuestionIds } from '../src/lib/xizongQuestionAttempts.mjs';
import { collectXizongRetainedEvidence } from '../src/lib/xizongRetainedPractice.mjs';
import { buildPrivateLearnerCheckpoint } from '../src/lib/privateLearnerCheckpoint.mjs';
import { writePrivateLearnerCheckpoint as diskWrite, readPrivateLearnerCheckpoint as diskRead, resolvePrivateLearnerDir } from './privateLearnerStore.mjs';
const root=path.resolve('..');""")
s=s.replace("head:process.env.GITHUB_SHA||'local'","head:process.env.XIZONG_AUDIT_HEAD||process.env.GITHUB_SHA||'local'")
old="for(let i=0;i<32;i++){await page.keyboard.press('Space');await page.keyboard.press(i%2?'2':'1');await page.waitForTimeout(155);}"
new="""for(let i=0;i<32;i++){
 const before=await state(page,studyKey);await page.locator('body').click({position:{x:1,y:1}});await page.keyboard.press('Space');
 await page.waitForFunction(()=>document.querySelector('[data-kp-recall-card]:not([hidden]) [data-kp-answer]')?.hidden===false);
 await page.keyboard.press(i%2?'2':'1');
 await page.waitForFunction(({key,prior,index})=>{const v=JSON.parse(localStorage.getItem(key));return Object.keys(v.ratings||{}).length===index+1&&(v.stage==='block_recall'||v.kpIndex!==prior);},{key:studyKey,prior:before.kpIndex,index:i});
 }"""
assert old in s;s=s.replace(old,new)
s=s.replace("assert.equal(Object.keys(s.ratings).length,0);return {learned:32,confirmations:1};", "assert.equal(Object.keys(s.ratings).length,0);assert.equal(s.sourceContactEvidence.length,1);assert.equal(s.sourceContactEvidence[0].kp_ids.length,32);return {learned:32,confirmations:1};")
old="const cdp=await c.newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');const doc=await cdp.send('DOM.getDocument');const q=await cdp.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'[data-kp-recall-card]:not([hidden]) h3'});const fonts=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:q.nodeId});return {os:process.platform,samples:rows,actualFonts:fonts};"
new="""await page.evaluate(()=>{const root=document.querySelector('[data-kp-recall-card]:not([hidden])');const el=[...root.querySelectorAll('*')].find(n=>n.childElementCount===0&&/[\\u4e00-\\u9fff]/.test(n.textContent)&&n.getBoundingClientRect().height>0&&getComputedStyle(n).visibility==='visible');if(!el)throw Error('No visible CJK');el.setAttribute('data-audit-font-target','');});
 const cdp=await c.newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');const doc=await cdp.send('DOM.getDocument');const q=await cdp.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'[data-audit-font-target]'});const fonts=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:q.nodeId});if(process.platform==='darwin')assert.ok(fonts.fonts.some(f=>/PingFang/.test(f.familyName)&&f.glyphCount>0));return {os:process.platform,samples:rows,actualFonts:fonts};"""
assert old in s;s=s.replace(old,new)
unit="""
await test('All 38 mature Blocks preserve complete Core and exact LG members through production',()=>{
 let count=0,kps=0;for(const system of listProjectableXizongSystems())for(const ref of system.blocks){
 const original=loadXizongBlock(system.systemId,ref.slug);const {block,learnerObject}=resolveXizongLearnerProjection(original);
 assert.equal(learnerObject.kps.length,original.kpRecords.length);assert.equal(new Set(learnerObject.logicGroups.flatMap(g=>g.kpIds)).size,original.kpRecords.length);
 for(const kp of original.kpRecords)assert.equal(learnerObject.kps.find(x=>x.identity.kpId===kp.kpId).core.markdown,kp.detailMarkdown);
 assert.equal(block.ttsx.checkpoints.length,0);count++;kps+=original.kpRecords.length;
 }return {blocks:count,kps,ttsx:'No reviewed release bound on these paths; absent is not fabricated'};
});
await test('Memory availability is not scheduled debt; Repair never rewrites Recall',()=>{
 const {learnerObject}=resolveXizongLearnerProjection(loadXizongBlock('circulation','b01'));const ids=learnerObject.kps.map(k=>k.identity.kpId);
 const study={completed:true,blockRecallDone:true,learned:Object.fromEntries(ids.map(id=>[id,true])),ratings:Object.fromEntries(ids.map(id=>[id,'mastered']))};
 const released=releaseCompletedBlockToMemory(null,learnerObject,study);assert.equal(released.released,true);assert.equal(todayMemoryQueue(released.state).length,0);assert.equal(releaseCompletedBlockToMemory(released.state,learnerObject,study).released,false);
 const original=JSON.stringify(study);const tasks=setRepairTasks(released.state,[{id:'synthetic-repair',kpId:ids[0],blockId:'circulation-b01',status:'ACTIVE'}]);completeRepairTask(tasks,'synthetic-repair');assert.equal(JSON.stringify(study),original);return {core:ids.length,automaticDebt:0};
});
await test('Formal attempts append; Stable clears WU but preserves Marked',()=>{
 const questions=loadXizongWholePaper(2026).questions.slice(0,2),ids=questions.map(q=>q.questionId);let i=0;const rt={now:'2026-09-19T01:00:00Z',makeId:()=>`synthetic-${++i}`};const ctx={questions,studyPhase:'FIRST_PASS',systemId:'test'};let st=ensureXizongQuestionSweepState(null,ctx,rt);
 for(let j=0;j<2;j++)st=recordXizongQuestionAttempt(st,{question:questions[j],selected:['A'],status:j?'stable':'wrong',context:ctx},rt);
 st=setXizongQuestionMarked(st,ids[1],true);assert.deepEqual(deriveXizongSecondPassQuestionIds(st,questions),[ids[0]]);assert.deepEqual(deriveXizongMarkedQuestionIds(st,questions),[ids[1]]);
 const first=JSON.stringify(st.attemptHistory[0]);st=startNextXizongQuestionRound(st,ids,rt,{studyPhase:'SECOND_PASS'});st=recordXizongQuestionAttempt(st,{question:questions[0],selected:['A'],status:'stable',context:ctx},{...rt,now:'2026-09-19T02:00:00Z'});
 assert.equal(st.attemptHistory.length,3);assert.equal(JSON.stringify(st.attemptHistory[0]),first);assert.deepEqual(deriveXizongSecondPassQuestionIds(st,questions),[]);assert.deepEqual(deriveXizongMarkedQuestionIds(st,questions),[ids[1]]);
});
await test('Private file persists across process restart outside repository and rejects invalid schema',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'xizong-private-audit-'));try{const packet=buildPrivateLearnerCheckpoint({studyDay:'2026-09-19',subjects:{xizong:{synthetic:true,sentinel:'not-U'}}});diskWrite(packet,dir);
 const text=execFileSync(process.execPath,['--input-type=module','-e',`import {readPrivateLearnerCheckpoint as read} from ${JSON.stringify(new URL('../scripts/privateLearnerStore.mjs',import.meta.url).href)};console.log(JSON.stringify(read(${JSON.stringify(dir)})))`],{encoding:'utf8'});assert.equal(JSON.parse(text).payload.subjects.xizong.sentinel,'not-U');assert.throws(()=>diskWrite({...packet,schema:'unsupported'},dir));assert.equal(diskRead(dir).payload.subjects.xizong.sentinel,'not-U');fs.writeFileSync(path.join(dir,'latest.json'),'{broken');assert.throws(()=>diskRead(dir));assert.equal(fs.readFileSync(path.join(dir,'latest.json'),'utf8'),'{broken');return {macDefault:resolvePrivateLearnerDir({env:{},platform:'darwin',home:'/synthetic-home'}),fileMode:fs.statSync(path.join(dir,'latest.json')).mode&0o777,automaticXizongCapture:'SEPARATELY_BLOCKED'};
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
"""
s=s.replace("const {chromium}=await import('playwright');",unit+"const {chromium}=await import('playwright');")
browser="""
 await test('Malformed local study state is retained and cannot fabricate progress',async()=>{const {c,page}=await context();try{await page.addInitScript(key=>localStorage.setItem(key,'{unreadable-original'),studyKey);await visit(page,'/xizong/circulation/b01/');assert.equal(await page.evaluate(k=>localStorage.getItem(k),studyKey),'{unreadable-original');assert.equal(await page.locator('[data-xizong-v6-block]').evaluate(n=>n.inert),true);await page.keyboard.press('Space');await page.keyboard.press('1');assert.equal(await page.evaluate(k=>localStorage.getItem(k),studyKey),'{unreadable-original');}finally{await c.close();}});
 await test('System Recall and System Practice remain locked without learner prerequisites',async()=>{const {c,page}=await context();try{await visit(page,'/xizong/circulation/recall/');await page.keyboard.press('Space');await page.keyboard.press('Enter');assert.equal((await state(page,'kianos:xizong:system-recall:circulation:v1'))?.completedAt||null,null);await visit(page,'/xizong/practice/circulation/');assert.equal(await page.locator('[data-question-card]').isVisible(),false);assert.ok((await page.locator('[data-chat-set-error-title]').textContent()).includes('System Recall'));await visit(page,'/xizong/hematology-immunity-infection/');assert.equal(await page.locator('[data-xizong-v6-block]').count(),0);}finally{await c.close();}});
 await test('System Recall dedicated neutral Front, Reveal, completion and Practice handoff',async()=>{const {c,page}=await context();try{const sys=loadXizongSystem('circulation');const seeded=Object.fromEntries(sys.blocks.map(b=>{const x=loadXizongBlock('circulation',b.slug);return [`kianos-xizong-astro-v2:xizong:${b.blockId}`,JSON.stringify({completed:true,blockRecallDone:true,learned:Object.fromEntries(x.kpRecords.map(k=>[k.kpId,true])),ratings:Object.fromEntries(x.kpRecords.map(k=>[k.kpId,'known']))})];}));await page.addInitScript(seed=>{for(const[k,v]of Object.entries(seed))localStorage.setItem(k,v);},seeded);await visit(page,'/xizong/circulation/recall/');assert.equal(await page.locator('[data-recall-reveal]').isVisible(),false);await page.screenshot({path:path.join(out,'system-recall-front.png')});await page.locator('[data-reveal-recall]').click();assert.equal(await page.locator('[data-recall-reveal]').isVisible(),true);await page.screenshot({path:path.join(out,'system-recall-reveal.png')});await page.locator('[data-complete-recall]').click();assert.ok((await state(page,'kianos:xizong:system-recall:circulation:v1')).completedAt);assert.ok((await page.locator('[data-practice-handoff]').textContent()).includes('训练'));}finally{await c.close();}});
 await test('CHAT_SET order, Stable fast exit, Uncertain review, unknown and Holdout refusal',async()=>{const {c,page}=await context();try{const first=loadXizongWholePaper(2026).questions[1],second=loadXizongWholePaper(2005).questions[2],ids=[first.questionId,second.questionId];const set={schema:'kianos.xizong.chat_set.v1',scope_type:'CHAT_SET',set_id:'synthetic-final-audit',label:'Synthetic audit',question_ids:ids,study_phase:'SECOND_PASS',result_visibility:'immediate',speed:'normal'};
 await visit(page,'/xizong/');await page.evaluate(s=>localStorage.setItem('kianos:xizong:chat-set:v1',JSON.stringify(s)),set);await visit(page,'/xizong/practice/chat-set/');assert.equal(await page.locator('[data-question-card]').isVisible(),true);assert.ok((await page.locator('[data-question-meta]').textContent()).includes('2026'));await page.screenshot({path:path.join(out,'practice-front.png')});await page.locator('[data-question-mark]').click();for(const a of String(first.correctAnswer).match(/[A-E]/g)||[])await page.locator(`[data-option="${a}"]`).click();await page.locator('[data-submit-answer]').click();await page.waitForFunction(()=>document.querySelector('[data-question-meta]')?.textContent.includes('2005'));assert.equal(await page.locator('[data-practice-back]').isVisible(),false);await page.locator('[data-question-uncertain]').click();for(const a of String(second.correctAnswer).match(/[A-E]/g)||[])await page.locator(`[data-option="${a}"]`).click();await page.locator('[data-submit-answer]').click();assert.equal(await page.locator('[data-practice-back]').isVisible(),true);await page.screenshot({path:path.join(out,'practice-back.png')});const entries=await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.includes('question-sweep')).map(k=>[k,localStorage.getItem(k)]));const retained=collectXizongRetainedEvidence(entries);assert.ok(retained.wrongUncertainIds.includes(ids[1]));assert.ok(!retained.wrongUncertainIds.includes(ids[0]));
 await page.evaluate(s=>{s.question_ids.push('xizong-official-2026-n999');localStorage.setItem('kianos:xizong:chat-set:v1',JSON.stringify(s));},set);await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('[data-question-card]').isVisible(),false);await page.evaluate(s=>{localStorage.setItem('kianos:xizong:chat-set:v1',JSON.stringify(s));localStorage.setItem('kianos:xizong:full-paper-holdout-years:v1','[2026]');},set);await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('[data-question-card]').isVisible(),false);}finally{await c.close();}});
 await test('Mixed unknown and real WU identities reject the whole Chat import',async()=>{const {c,page}=await context();try{await visit(page,'/xizong/');await page.evaluate(()=>{localStorage.setItem('kianos:xizong:system-recall:circulation:v1',JSON.stringify({completedAt:new Date().toISOString()}));localStorage.setItem('kianos:xizong:full-paper-holdout-years:v1','[]');});await visit(page,'/xizong/practice/circulation/');const q=loadXizongSystemQuestionSweep(loadXizongSystem('circulation')).questions.find(q=>q.relation?.primaryKpId);assert.ok(q);await page.evaluate(q=>localStorage.setItem('kianos:xizong:system-question-sweep:circulation:v1',JSON.stringify({results:{[q.questionId]:{status:'wrong',selected:['A'],attemptId:'synthetic-wrong'}}})),q);const before=await page.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(k=>/repair|memory/.test(k)).map(k=>[k,localStorage.getItem(k)])));await page.locator('[data-xizong-repair-return] summary').click();await page.locator('[data-plan-text]').fill(JSON.stringify({plan:[{question_id:q.questionId,action:'synthetic repair'},{question_id:'xizong-official-2026-n999',action:'must not partially apply'}]}));await page.locator('[data-apply-plan]').click();const after=await page.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(k=>/repair|memory/.test(k)).map(k=>[k,localStorage.getItem(k)])));assert.deepEqual(after,before);return {rejectedBeforeWrite:true,typedRoundTrip:'not supplied by legacy transport'};}finally{await c.close();}});
"""
anchor=" await test('Current Mac-wide heterogeneous visible geometry and environment evidence'"
assert anchor in s;s=s.replace(anchor,browser+anchor)
p.write_text(s)
print('independent probes extended; known shared blockers remain failures, not waived')
