from pathlib import Path
R=Path.cwd()/'static-web'
p=R/'scripts/english-final-fresh-audit.mjs';s=p.read_text().replace("import * as ledger from '../src/lib/lexicalEvidence.mjs';","import * as ledger from '../src/lib/lexicalEvidence.mjs';\nimport * as wr from '../src/lib/writingRuntimeModel.mjs';\nimport * as ev from '../src/lib/englishTaskEvidence.mjs';")
extra='''
const at=new Date(t).toISOString(),later=new Date(t+1000).toISOString();
const wt={id:'audit-writing',kind:'small',sourceKind:'synthetic',sourceHash:'audit-content-v1',learnerTask:{directions:'Write independently.'}};
const freshWriting=()=>wr.lockFirstAttempt(wr.createInitialWritingRecord(wt),{planMode:'direct',firstDraft:'My independently generated first draft.'},at);
const review=(r)=>({schema:wr.WRITING_REVIEW_RETURN_SCHEMA,...ev.englishReturnBinding(r),taskId:wt.id,reviewOf:'FIRST_DRAFT',verdict:'REPAIR_NEEDED',firstFailureLayer:'Content',repairScope:'body',smallestRepair:'Supply the missing practical detail yourself.',reason:'One required detail is absent.'});
check('WRITING stale same-task first-draft return rejected',()=>{const a=freshWriting(),p=review(a);a.firstSubmittedAt=later;assert.throws(()=>wr.applyWritingReviewReturn(a,p));assert.equal(a.state,'REVIEW_PENDING');});
check('WRITING repair replay cannot erase learner regeneration',()=>{const p=review(freshWriting());let r=wr.applyWritingReviewReturn(freshWriting(),p,at);r.regenerationDraft='My ongoing regeneration.';assert.deepEqual(wr.applyWritingReviewReturn(r,p,later),r);});
check('WRITING learner regeneration exact return and replay',()=>{let r=wr.applyWritingReviewReturn(freshWriting(),review(freshWriting()),at);r=wr.lockWritingRegeneration(r,'Learner supplies the practical detail.',later);const p={schema:wr.WRITING_REPAIR_RETURN_SCHEMA,...ev.englishReturnBinding(r,true),taskId:wt.id,repairOf:'REGENERATION',verdict:'REPAIR_COMPLETE',reason:'The missing detail was independently supplied.',memoryAdmission:{admit:false}};const done=wr.applyWritingRepairReturn(r,p,later);assert.equal(done.state,'REPAIR_COMPLETE');assert.equal(done.firstDraft,r.firstDraft);assert.deepEqual(wr.applyWritingRepairReturn(done,p),done);assert.throws(()=>wr.applyWritingRepairReturn(r,{...p,regenerationSubmittedAt:at}));});
check('WRITING terminal flag alone is not cold-start evidence',()=>assert.equal(wr.syntheticTaskQualifiesForColdStartExit({state:'PASS_ACCEPTABLE',sourceKind:'synthetic'}),false));
const freshTranslation=()=>{const a=tr.blankTranslationState(prompts);a.drafts={p1:'My first translation one',p2:'My first translation two'};return tr.freezeWholeAttempt(a,prompts,at).state;};
const trReturn=(r)=>({schema:tr.TRANSLATION_RETURN_SCHEMA,...ev.englishReturnBinding(r),task:'audit-translation',decision:'REPAIR_NEEDED',primary_failure:{layer:'English Representation',affected_segments:['p1'],minimal_repair:'Resolve the reference, then translate independently.'},transfer_updates:[]});
check('TRANSLATION exact return stays whole-set and preserves first output',()=>{const a=freshTranslation(),p=trReturn(a);const b=tr.applyTranslationReturn(a,p,prompts,null,{task:'audit-translation'}).state;assert.equal(b.stage,'reconstruct');assert.deepEqual(b.firstAttempts,a.firstAttempts);assert.deepEqual(b.affectedSegments,['p1']);});
check('TRANSLATION stale attempt and invalid segment returns reject atomically',()=>{const a=freshTranslation(),raw=JSON.stringify(a),p=trReturn(a);assert.throws(()=>tr.applyTranslationReturn(a,{...p,attemptSubmittedAt:later},prompts,null,{task:'audit-translation'}));assert.throws(()=>tr.applyTranslationReturn(a,{...p,primary_failure:{...p.primary_failure,affected_segments:['invented']}},prompts,null,{task:'audit-translation'}));assert.equal(JSON.stringify(a),raw);});
check('TRANSLATION replay preserves in-progress learner Reconstruction',()=>{const a=freshTranslation(),p=trReturn(a);const b=tr.applyTranslationReturn(a,p,prompts,null,{task:'audit-translation'}).state;b.reconstructDrafts.p1='My own ongoing repair';assert.deepEqual(tr.applyTranslationReturn(b,p,prompts,null,{task:'audit-translation'}).state,b);});
check('LEXICAL Current resolver rejects invented sense and wrong Word',()=>{const e=event(at),current={word_id:e.word_id,ordinal:e.ordinal,source_revision:'v1',targets:[{target_kind:e.target_kind,target_id:e.target_id,target_locator:'record.senses[0]'}]};assert.doesNotThrow(()=>lex.assertCurrentLexicalTarget(e,current));assert.throws(()=>lex.assertCurrentLexicalTarget({...e,target_id:'invented'},current));assert.throws(()=>lex.assertCurrentLexicalTarget(e,{...current,word_id:'other'}));});
check('LEXICAL locator-only target requires exact Current revision',()=>{const e={...event(at),target_id:null,target_locator:'record.senses[0]',target_revision:'v1'};const current={word_id:e.word_id,ordinal:e.ordinal,source_revision:'v1',targets:[{target_kind:e.target_kind,target_id:null,target_locator:e.target_locator}]};assert.doesNotThrow(()=>lex.assertCurrentLexicalTarget(e,current));assert.throws(()=>lex.assertCurrentLexicalTarget({...e,target_revision:'v0'},current));});
check('LEXICAL supplied event id cannot collapse distinct attempts',()=>{const th=structuredClone(thread);th.lexicalEvidence.event_id='same-user-supplied-id';const a=lex.lexicalEventFromObjectiveThread({task:'writing',objectId:'audit-writing',attemptSubmittedAt:at,thread:th}).event,b=lex.lexicalEventFromObjectiveThread({task:'writing',objectId:'audit-writing',attemptSubmittedAt:later,thread:th}).event;assert.notEqual(a.event_id,b.event_id);});
check('EXPOSURE absence remains UNKNOWN; initial Content metadata is not learner history',()=>assert.equal(ev.englishMaterialExposure(storage(),'audit-reading').state,'UNKNOWN'));
check('EXPOSURE ordinary and exam facts meet without sharing answers',()=>{const st=storage(),s=initial();st.setItem('kianos-reading-attempt-v1:audit-reading',{toString:()=>JSON.stringify({startedAt:at,answers:{q:'B'}})});assert.equal(ev.englishMaterialExposure(st,'audit-reading').state,'EXPOSED');const c=exam.captureEnglishExamStep(s,{stepId:'s0',task:'cloze',objectId:'audit-cloze-0',payload:{answers:{q:'A'}},now:t+1000});exam.writeEnglishExamSession(st,c);assert.equal(ev.englishMaterialExposure(st,'audit-cloze-0').state,'EXPOSED');assert.equal(JSON.parse(st.getItem('kianos-reading-attempt-v1:audit-reading')).answers.q,'B');});
check('EVIDENCE changed Current content is not silently reinterpreted',()=>{const c={id:'audit-reading',sourceHash:'v1'};const value=ev.bindEnglishTaskEvidence({answers:{q:'A'}},c);const raw=JSON.stringify(value);assert.throws(()=>ev.assertEnglishTaskEvidence(raw,{...c,sourceHash:'v2'}));assert.equal(JSON.parse(raw).answers.q,'A');});
check('EVIDENCE legacy output never receives retrospective Current provenance',()=>{const c={id:'audit-reading',sourceHash:'v2'};const old=JSON.stringify({answers:{q:'A'},submitted:true});const value=ev.bindEnglishTaskEvidence({answers:{q:'A'},submitted:true},c,old);assert.equal(value.legacy_source_binding,'UNVERIFIED');assert.equal(value.evidence_binding,undefined);});
'''
s=s.replace('const report={',extra+'\nconst report={');p.write_text(s)
p=R/'scripts/english-final-fresh-browser.mjs';s=p.read_text();a=s.index("await run('reading-first-answer-survives-retry'");b=s.index("await run('uncertain",a)
s=s[:a]+'''await run('reading-first-answer-survives-refresh-and-post-submit-change',async p=>{await go(p,'/reading/audit-reading-0/','[data-question]');await p.locator('[data-question]').first().locator('[data-option="B"]').click();await p.locator('[data-reading-submit]').click();await p.waitForFunction(k=>JSON.parse(localStorage.getItem(k)||'{}').submitted,ra);const first=await data(p,ra);assert.equal(first.history[0].answers['audit-reading-0-q0'],'B');await p.reload();await p.waitForTimeout(500);const next=await data(p,ra);assert.equal(next.history[0].answers['audit-reading-0-q0'],'B');assert.equal(next.history[0].submittedAt,first.submittedAt);assert.equal(await p.locator('[data-reading-retry]:visible').count(),0);});
'''+s[b:]
extra='''
const keysSnapshot=async(p,keys)=>p.evaluate(ks=>Object.fromEntries(ks.map(k=>[k,localStorage.getItem(k)])),keys);
await run('objective-exact-return-atomic-replay-and-current-lexical-target',async p=>{
 await go(p,'/reading/audit-reading-0/','[data-question]');for(let i=0;i<5;i++)await p.locator('[data-question]').nth(i).locator('[data-option="B"]').click();await p.locator('[data-reading-submit]').click();await p.waitForFunction(k=>JSON.parse(localStorage.getItem(k)||'{}').submitted,ra);
 const a=await data(p,ra),current=await (await p.request.get(base+'/vocabulary/targets/1.json')).json();const target=current.targets.find(t=>t.target_kind==='sense'&&t.target_id);
 const payload={schema:'kianos.english.objective_review_return.v1',task:'reading_a',objectId:'audit-reading-0',attemptSubmittedAt:a.submittedAt,contentRevision:a.evidence_binding.content_revision,threads:[{threadId:'lex1',route:'lexical',scope:'local',itemIds:['audit-reading-0-q0'],summary:'The exact sense was not available.',repairCompleted:false,lexicalEvidence:{word_id:current.word_id,ordinal:current.ordinal,target_kind:target.target_kind,target_id:target.target_id,target_locator:target.target_locator,outcome:'WRONG',demand:'discrimination'}}],newClaims:[],claimUpdates:[]};
 const keys=['kianos-english-objective-review-return-v1:reading_a:audit-reading-0','kianos-english-objective-transfer-claims-v1','kianos-lexical-evidence-ledger-v2','kianos-vocabulary-astro-v2:'+current.word_id];
 const enter=async value=>{if(!await p.locator('[data-transfer-input]').isVisible())await p.locator('[data-transfer-toggle]').click();await p.locator('[data-transfer-input]').fill(JSON.stringify(value));await p.locator('[data-transfer-apply]').click();await p.waitForTimeout(700);};
 const before=await keysSnapshot(p,keys),bad=structuredClone(payload);bad.threads[0].lexicalEvidence.target_id='invented-sense';await enter(bad);assert.deepEqual(await keysSnapshot(p,keys),before);assert((await p.locator('[data-transfer-status]').innerText()).includes('未应用'));
 const mixed=structuredClone(payload);mixed.newClaims=[{statement:'must reject this unbound claim',sourceThreadId:'missing'}];await enter(mixed);assert.deepEqual(await keysSnapshot(p,keys),before);
 await enter(payload);const after=await keysSnapshot(p,keys);assert(after[keys[0]]);assert.equal(JSON.parse(after[keys[0]]).attemptSubmittedAt,a.submittedAt);assert(Object.keys(JSON.parse(after[keys[3]]).repairTargets).length>0);await enter(payload);assert.deepEqual(await keysSnapshot(p,keys),after);
 const stale={...payload,attemptSubmittedAt:'2000-01-01T00:00:00Z'};await enter(stale);assert.deepEqual(await keysSnapshot(p,keys),after);
});
await run('lexical-read-only-lookup-and-exact-origin-return',async p=>{
 await go(p,'/reading/audit-reading-0/','[data-question]');await p.locator('[data-question]').nth(3).locator('[data-option="B"]').click();const before=await data(p,ra);
 const lexical=()=>p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(k=>/vocab|lexical/.test(k)).map(k=>[k,localStorage.getItem(k)])));
 const prior=await lexical();await p.evaluate(()=>sessionStorage.setItem('kianos-english-lexical-return-v1',JSON.stringify({schema:'kianos.english.lexical_return.v1',returnHref:'/reading/audit-reading-0/',task:'Reading A',objectId:'audit-reading-0',word:'a',sourceScrollTop:0,windowScrollY:0,createdAt:new Date().toISOString(),returning:false})));
 await go(p,'/vocabulary/1/?mode=lookup&from=english','[data-local-port="vocabulary"]');assert.equal(await p.locator('[data-local-port="vocabulary"]').getAttribute('data-vocab-mode'),'lookup');assert.deepEqual(await lexical(),prior);await p.locator('[data-english-return-action]').click();await p.waitForURL('**/reading/audit-reading-0/');await p.waitForTimeout(500);const returned=await data(p,ra);assert.deepEqual(returned.answers,before.answers);assert.equal(returned.currentIndex,before.currentIndex);
});
await run('guides-addressable-skippable-not-progress-gates',async p=>{for(const [path,selector]of [['/objective-learn/','#ra-core-2'],['/translation-learn/','h1'],['/writing-learn/','h1']]){await go(p,path,selector);assert(await p.locator('a[href*="/reading/"],a[href*="/translation/"],a[href*="/writing/"]').count()>0);}await shot(p,'first-learning');});
await run('exam-cannot-mutate-or-reveal-preexisting-ordinary-reading',async p=>{
 await go(p,'/reading/audit-reading-0/','[data-question]');for(let i=0;i<5;i++)await p.locator('[data-question]').nth(i).locator('[data-option="B"]').click();await p.locator('[data-reading-submit]').click();await p.waitForFunction(k=>JSON.parse(localStorage.getItem(k)||'{}').submitted,ra);const before=await p.evaluate(k=>localStorage.getItem(k),ra);let requested=[];p.on('request',r=>{if(r.url().includes('reading-answer/'))requested.push(r.url());});
 await go(p,'/english-exam/audit-paper/','[data-exam-start]');await p.locator('[data-exam-start]').click();await p.waitForURL('**/cloze/audit-cloze/**');await p.locator('[data-exam-complete]').click();await p.waitForURL('**/reading/audit-reading-0/**');await p.waitForTimeout(300);assert.equal(requested.length,0);assert.equal(await p.evaluate(k=>localStorage.getItem(k),ra),before);assert.equal(await p.locator('.objectiveTransferPanel:visible').count(),0);await p.locator('[data-question]').first().locator('[data-option="A"]').click();assert.equal(await p.evaluate(k=>localStorage.getItem(k),ra),before);
});
await run('browser-process-restart-preserves-first-draft-and-binding',async()=>{
 const dir=fs.mkdtempSync(out+'/profile-');let ctx;
 try {ctx=await chromium.launchPersistentContext(dir,{headless:true,viewport:{width:1512,height:982}});let p=await ctx.newPage();await go(p,'/writing/audit-writing-small/','[data-essay-draft]');await p.locator('[data-essay-draft]').fill('The first draft survives an actual browser process restart.');await p.locator('[data-lock-first]').click();const key='kianos-writing-runtime-v1:audit-writing-small',before=await data(p,key);await ctx.close();ctx=await chromium.launchPersistentContext(dir,{headless:true,viewport:{width:1512,height:982}});p=await ctx.newPage();await go(p,'/writing/audit-writing-small/','[data-writing-runtime]');const after=await data(p,key);assert.equal(after.firstDraft,before.firstDraft);assert.equal(after.firstSubmittedAt,before.firstSubmittedAt);assert.deepEqual(after.evidence_binding,before.evidence_binding);
 }finally{await ctx?.close();fs.rmSync(dir,{recursive:true,force:true});}
});
'''
s=s.replace('await browser.close();const failed=',extra+'\nawait browser.close();const failed=');p.write_text(s)
