#!/usr/bin/env python3
"""Reusable mechanical primitives for cross-Word Lexical relations.

This module carries no semantic authority. Callers must supply an already-frozen
relationship and exact Word owners. It writes the relation views into canonical
Word bundles before Natural Owner materialization so relation_refs and the
Relation Natural Owner are generated by the normal lossless build path.
"""
from __future__ import annotations

import copy
import hashlib
import json
from pathlib import Path
from typing import Any


def stable_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def relation_id(relation_type: str, words: tuple[str, str]) -> str:
    key = {"relation_type": relation_type, "words": sorted(words)}
    return "relation:horizontal:" + hashlib.sha256(stable_json(key).encode("utf-8")).hexdigest()[:20]


def attach_reciprocal_spelling_variant(
    store,
    *,
    left_ordinal: int,
    left_word: str,
    left_word_id: str,
    left_region: str,
    right_ordinal: int,
    right_word: str,
    right_word_id: str,
    right_region: str,
    boundary: str,
) -> str:
    """Attach one reciprocal spelling-variant relation to two existing Word owners.

    Both Word identities remain intact. No sense identity is copied across Words.
    Existing identical views are reused; conflicting same-ID views fail closed.
    """
    rid = relation_id("spelling_variant", (left_word, right_word))

    def payload(source: str, target: str, target_word: str, region: str) -> dict[str, Any]:
        return {
            "relation_id": rid,
            "relation_type": "spelling_variant",
            "relation_scope": "lexeme",
            "direction": "C",
            "priority": "A",
            "publication_status": "codex_reviewed",
            "verification_status": "verified",
            "writing_safe": True,
            "source_expression": source,
            "target_expression": target,
            "target_word": target_word,
            "boundary": boundary,
            "boundaries": [boundary],
            "learning_note": boundary,
            "task_tags": ["reading", "writing"],
            "regional_label": region,
        }

    pairs = (
        (left_ordinal, left_word_id, payload(left_word, right_word, right_word, left_region)),
        (right_ordinal, right_word_id, payload(right_word, left_word, left_word, right_region)),
    )
    for ordinal, expected_word_id, view in pairs:
        rec = store.record(ordinal)
        if rec.get("word_id") != expected_word_id:
            raise RuntimeError(
                f"RELATION_WORD_ID_MISMATCH o{ordinal:04d} expected={expected_word_id} actual={rec.get('word_id')}"
            )
        arr = rec.setdefault("semantic_neighbors", [])
        same = [x for x in arr if isinstance(x, dict) and x.get("relation_id") == rid]
        if same:
            if len(same) != 1 or stable_json(same[0]) != stable_json(view):
                raise RuntimeError(f"RELATION_VIEW_CONFLICT {rid} o{ordinal:04d}")
        else:
            arr.append(copy.deepcopy(view))
            store.mark(ordinal)
    return rid


def materialize_relation_owner(*, relation_owners: dict[str, dict[str, Any]], rid: str, root: Path, dump_json) -> Path:
    """Write the Natural Owner produced by the canonical-word relation views."""
    if rid not in relation_owners:
        raise RuntimeError(f"RELATION_OWNER_NOT_MATERIALIZED {rid}")
    digest = hashlib.sha256(rid.encode("utf-8")).hexdigest()
    path = root / "content" / "lexical" / "relations" / "by-id" / digest[:2] / f"{digest}.json"
    dump_json(path, relation_owners[rid])
    return path
